name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ${{ env.HOME }}/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Restore dependencies from cache
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.name 'GitHub Actions' && git config --global user.email 'actions@github.com'

      - name: Get Commit Message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Create Tag
        id: create_tag
        run: echo "::set-output name=tag::$(echo ${{ github.sha }} | cut -c 1-6)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.VORG_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: Release ${{ github.sha }}
          body: ${{ steps.commit_message.outputs.message }}
          draft: false
          prerelease: false
