name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ${{ env.HOME }}/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Restore dependencies from cache
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.name 'GitHub Actions' && git config --global user.email 'actions@github.com'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.VORG_TOKEN }}
        with:
          tag_name: ${{ github.sha }}[:6]
          release_name: Release ${{ github.sha }}
          body: |
            This is an automatically generated release.
          draft: false
          prerelease: false
